# .github/workflows/supabase-migrations.yml
# Secret required: SUPABASE_DB_URL
# Example: postgres://USER:PASSWORD@HOST:5432/DB?sslmode=require

name: Supabase Migrations (Direct)

on:
  push:
    branches: [ main ]
    paths:
      - "supabase/migrations/**/*.sql"
  pull_request:
    branches: [ main ]
    paths:
      - "supabase/migrations/**/*.sql"
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      MIGRATIONS_DIR: supabase/migrations
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run migrations
        shell: bash
        run: |
          set -euo pipefail

          psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -c "
          CREATE TABLE IF NOT EXISTS public.schema_migrations (
            filename text PRIMARY KEY,
            applied_at timestamptz NOT NULL DEFAULT now()
          );"

          if [ ! -d "$MIGRATIONS_DIR" ]; then
            echo "No '$MIGRATIONS_DIR' directory. Nothing to do."
            exit 0
          fi

          mapfile -t FILES < <(find "$MIGRATIONS_DIR" -type f -name '*.sql' | sort)
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "No .sql files. Nothing to do."
            exit 0
          fi

          for f in "${FILES[@]}"; do
            name="$(basename "$f")"
            applied="$(psql "$SUPABASE_DB_URL" -At -c \
              "SELECT 1 FROM public.schema_migrations WHERE filename = '$name' LIMIT 1" || true)"
            if [ -z "$applied" ]; then
              echo "Applying: $name"
              psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -1 -f "$f"
              psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -c \
                "INSERT INTO public.schema_migrations (filename) VALUES ('$name');"
            else
              echo "Skip: $name"
            fi
          done
